server:
  port: 8090
spring:
  redis:
    database: 1
    host: 47.94.194.140
    port: 6379
    password: cwt521..      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
feign:
  hystrix:
    enabled: true